[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

# Ignorer le kernel par défaut — ShivaOS utilise linux-shivaos
IgnorePkg = linux linux-headers

[shivaos]
SigLevel = Required DatabaseOptional TrustAll
Server = https://shivaos.com/arch-repo/x86_64
Server = https://freuja-wq.github.io/shivaos-arch-repo/x86_64

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist


